# Generated by Django 5.2.4 on 2025-07-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='Autor',
            field=models.CharField(max_length=50),
        ),
    ]
